### ISSUE TITLE
Incorrect snippet format if quotes present

### ISSUE THREAD

**Issue by adrianlzt** [pearofducks/ansible-vim#90]
This generated snippet is incorrect and breaks UltiSnips
```
snippet cp_mgmt_run_ips_update "Runs IPS database update. If "package-path" is not provided server will try to get the latest package from the User Center." b
```

The error (from a fake snippet to return the error):
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/adrian/.config/nvim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/adrian/.config/nvim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 896, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/adrian/.config/nvim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 788, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/adrian/.config/nvim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 668, in _snips
    source.ensure(filetypes)
  File "/home/adrian/.config/nvim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/home/adrian/.config/nvim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/adrian/.config/nvim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid multiword trigger: 'prueba "pr "ue' in ~/.config/nvim/UltiSnips/yaml.snippets:1
```

Looks like having quotes inside the quotes break UltiSnips

**Comment by pearofducks** [comment]
Regression vs. latest ansible.

Can you try to regenerate snippets using the `snippet-delimiter` branch, and let me know if things work OK?

**Comment by adrianlzt** [comment]
Now it breaks in:
```
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid multiword trigger: 'rundeck_project 'Manage Rundeck projects.' b' in ~/.config/nvim/bundle/ansible-vim/UltiSnips/ansible.snippets:5                                                                                                                                                                                          
```

Maybe something simpler like:
```
-    snippet.insert(0, "snippet %s '%s' b" % (document['module'], document['short_description']))
+    snippet.insert(0, 'snippet %s "%s" b' % (document['module'], document['short_description'].replace('"', '')))
```

**Comment by pearofducks** [comment]
Good idea. I've modified the branch and will merge it soon.
